---
version: '3.6'

volumes:
  prometheus-testnet:
  prometheus-mainnet:
  prometheus-arabian:

networks:
  bharatblockchain:
    name: bharatblockchain
    driver: bridge
    ipam:
      config:
        - subnet: 172.16.239.0/24


services:
  prometheus:
    image: "prom/prometheus"
    volumes:
      - ./config/prometheus-testnet.yml:/etc/prometheus/prometheus-testnet.yml
      - prometheus-testnet:/prometheus
    command:
      - --config.file=/etc/prometheus/prometheus-testnet.yml
    ports:
      - 9090:9090/tcp
    networks:
      bharatblockchain:
        ipv4_address: 172.16.239.32
  prometheus-mainnet:
    image: "prom/prometheus"
    volumes:
      - ./config/prometheus-mainnet.yml:/etc/prometheus/prometheus-mainnet.yml
      - prometheus-mainnet:/prometheus
    command:
      - --config.file=/etc/prometheus/prometheus-mainnet.yml
    ports:
      - 9091:9090/tcp
    networks:
      bharatblockchain:
        ipv4_address: 172.16.239.33
  prometheus-arabian:
    image: "prom/prometheus"
    volumes:
      - ./config/prometheus-arabian.yml:/etc/prometheus/prometheus-arabian.yml
      - prometheus-arabian:/prometheus
    command:
      - --config.file=/etc/prometheus/prometheus-arabian.yml
    ports:
      - 9092:9090/tcp
    networks:
      bharatblockchain:
        ipv4_address: 172.16.239.34